# Generated by Django 4.1.7 on 2023-06-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_apk', '0004_rename_customerreview_clientappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookedBy', models.CharField(max_length=30)),
                ('reason', models.TextField()),
                ('isVisible', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ClientAppointment',
        ),
    ]
