# Generated by Django 4.1.7 on 2023-06-06 03:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oneset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=225)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('F', 'First Aid'), ('O', 'Observation'), ('I', 'Emergency'), ('I', 'Discharge'), ('E', 'Dead')], default='P', max_length=1)),
                ('address', models.CharField(max_length=225)),
                ('quotation', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oneset.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oneset.location')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('pincode', models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(7)])),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('value', models.PositiveIntegerField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient_management.appointment')),
                ('paymode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oneset.paymode')),
            ],
        ),
        migrations.CreateModel(
            name='staffPaymentLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('creditValue', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('debtValue', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('narration', models.CharField(max_length=700)),
                ('accountBalance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accountLedger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentWorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatureCheckup', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('N', 'None')], default='N', max_length=1)),
                ('weightMeasurement', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('N', 'None')], default='N', max_length=1)),
                ('xray', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('N', 'None')], default='N', max_length=1)),
                ('scanning', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('N', 'None')], default='N', max_length=1)),
                ('physiotherapy', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('N', 'None')], default='N', max_length=1)),
                ('plateletsCheckup', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('N', 'None')], default='N', max_length=1)),
                ('bpCheckup', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('N', 'None')], default='N', max_length=1)),
                ('dialysis', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('N', 'None')], default='N', max_length=1)),
                ('urinalysis', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('N', 'None')], default='N', max_length=1)),
                ('operationRequired', models.CharField(choices=[('D', 'Done'), ('P', 'Pending'), ('N', 'None')], default='N', max_length=1)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='patient_management.appointment')),
            ],
            options={
                'verbose_name': 'appointment Work Status',
                'verbose_name_plural': 'appointment Work Status',
            },
        ),
        migrations.CreateModel(
            name='appointmentStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='patient_management.appointment')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oneset.role')),
                ('user', models.ForeignKey(limit_choices_to={'is_active__iexact': 1, 'is_staff__iexact': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='appointmentPays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='mutuals',
            field=models.ManyToManyField(related_name='mutualAppointments', to='patient_management.client'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patient_management.client'),
        ),
    ]
